#!/bin/bash
#----------------------------------------------------------
# Job name
#PBS -N epochs_2000__batch_1000__arch_Tanh--32__Tanh--32__Tanh--32__Tanh--32

#PBS -o error_files/epochs_2000__batch_1000__arch_Tanh--32__Tanh--32__Tanh--32__Tanh--32.o

#PBS -e output_files/epochs_2000__batch_1000__arch_Tanh--32__Tanh--32__Tanh--32__Tanh--32.e

# Run time (hh:mm:ss) - 5 min
#PBS -l walltime=12:00:00
#----------------------------------------------------------

#PBS -l nodes=compute-0-0:ppn=1

# Change to submission directory
cd $PBS_O_WORKDIR

cat $PBS_NODEFILE

# Launch MPI-based executable
time .conda/envs/torch_gpu/bin/python3 edo_pinn_model.py -f k--0.0001__phi--0.2__ksi--0.0__cb--0.15__Cn_max--0.55__lambd_nb--1.8__mi_n--0.2__lambd_bn--0.1__y_n--0.1__t_lower--0.0__t_upper--10.0 -n 2000 -b 1000 -a Tanh--32__Tanh--32__Tanh--32__Tanh--32